server:
  port: 8082
#mysql
spring:
  application:
    name: app-buyer
  datasource:
    url: jdbc:mysql://localhost:3306/emart_buyer?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
# Specify the DBMS
  jpa:
     database: MYSQL
# Show or not log for each sql query
     show-sql: true
    #  generate-ddl: true
# Hibernate ddl auto (create, create-drop, update)
     hibernate:
       ddl-auto: update
  main:
    allow-bean-definition-overriding: true 
app-item:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true
eureka:
  client:
    service-url:
           defaultZone: http://127.0.0.1:9100/eureka
    register-with-eureka: true
    fetch-registry: true